language: elixir
matrix:
  include:
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.5

env:
 global:
   - MIX_ENV=test

before_install:
  # Install libcouchbase
  - wget http://packages.couchbase.com/releases/4.5.1/couchbase-server-community_4.5.1-ubuntu12.04_amd64.deb
  - sudo dpkg -i couchbase-server-community_4.5.1-ubuntu12.04_amd64.deb
  - wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-amd64.deb
  - sudo dpkg -i couchbase-release-1.0-2-amd64.deb
  - sleep 30
  - "curl -u Administrator:Administrator -v -X POST http://localhost:8091/node/controller/setupServices -d 'services=kv%2Cn1ql%2Cindex'"
  - "curl -v -X POST http://localhost:8091/nodes/self/controller/settings -d 'path=%2Fopt%2Fcouchbase%2Fvar%2Flib%2Fcouchbase%2Fdata&index_path=%2Fopt%2Fcouchbase%2Fvar%2Flib%2Fcouchbase%2Fdata'"
  - "curl -v -X POST http://localhost:8091/settings/web -d 'password=Administrator&username=Administrator&port=SAME'"
  - "curl -u Administrator:Administrator -v -X POST http://localhost:8091/pools/default/buckets -d 'flushEnabled=1&threadsNumber=3&replicaIndex=0&replicaNumber=0&evictionPolicy=valueOnly&ramQuotaMB=597&bucketType=couchbase&name=default&authType=sasl&saslPassword='"
  - "curl -u Administrator:Administrator -X POST http://localhost:8091/pools/default -d 'memoryQuota=2048' -d 'indexMemoryQuota=512'"
  - sudo apt-get update
  - sudo apt-get install libcouchbase-dev libcouchbase2-bin build-essential libstdc++6 libc6 g++ llvm clang runit wget python-httplib2
  # Install rustup and rust
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup update
  - rustc -Vv
  - cargo -V
  - rustup default nightly
  - rustup component add rust-src
  - export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src
  - export RUST_BACKTRACE=1

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

script:
  - cargo build
  - mix deps.compile
  - mix compile
  - mix check

cache:
  - bundler
  - cargo
