[package]
name = "gauc"
version = "0.1.0"
authors = []

[lib]
name = "gauc"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
# dyon = "0.24.7"
rustler = "0.15.1"
rustler_codegen = "0.15.1"
lazy_static = "0.2"
gauc = { git = "https://github.com/korczis/gauc" }